server:
  port: 8768

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123456@${eureka.instance.hostname}:8761/eureka/

spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/sp_test?userUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
  user:
    name: admin
    password: 123456
  application:
    name: user-server
  cloud:
   config:
     name: eureka-producer
     label: master
     profile: test
     enabled: true
     fail-fast: false
     retry:
       max-attempts: 6


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.user_service.bean

#showSql
logging:
  level:
    com:
      example:
        mapper : debug